metadata_file: 'metadata_file.csv' # if making metadata file before running this snakemake, make sure the file name is metadata_file.csv. Otherwise, keep the file name as is.
analysis_batch_name: 'batchname' # name for freebayes vcf file. If YYYYMMDD, current date will be used as name
genomeBuild: 'GRCh38' #GRCh37 (hg19), GRCh38 (hg38), or any other values to use ref_genome and bwa-mem2_ref below.
ped: '' #Can leave as blank ''. Only for ChrX CNV, has to have ped extenstion, header if present has to starts with #, ie miseq0626_0719.ped
inputFileType: 'fastq' # single_lane_fastq, fastq, bam or cram.
bed: '/data/OGL/resources/bed/OGLv1.GRCh38.sorted.bed' # bed file is used for coverage of eyeGene
padded_bed: '/data/OGL/resources/bed/xgenV2_OGLv1.500padded.bed' #for deepvariant variant calling in exome & panel
real_bed: 'FALSE' # TRUE or FALSE, if a real bed is provided, use the bed above for freebayes filtering. If not real_bed, then the bed above is used for deepvariant, but not for freebayes filtering.
markDup: 'TRUE' # TRUE, FALSE
cram: 'TRUE' # TRUE to convert bam to cram, values other than TRUE will not convert. #Keep bam for panel and exome if addtional analyses are anticipated
#recal_bam: 'FALSE' #TRUE to merge chr bams to single sample recalibrated bam
multiqc: 'TRUE' # will run only if TrueSeq
picardQC: 'TRUE'
CoNVaDING: 'FALSE'
SCRAMble: 'TRUE' #will run only if TRUE
GATKgvcf: 'FALSE' # will run only if TRUE
cutadapt: 'FALSE' #TRUE to trim adaptor using cutadapt, #FALSE not to trim.
regions: '/home/$USER/git/NGS_genotype_calling/NGS_generic_OGL/chr_split_24_coords.txt' #chr1 to chr22, chrX, chrY
deepvariant: 'TRUE'
#deepvariantGVCFmerge: 'FALSE' #GVCF files from deepvariant will be merged.
freebayes_phasing: 'TRUE'
coverage: 'TRUE'
manta: 'TRUE'
lane_pair_delim: ['_R1_001.fastq', '_R2_001.fastq'] #OGL & DavidM:'_R1_001', '_R2_001'
#samples: ['41001412010527_realigned_recal']
#read_groups: ['@RG\\tID:Lineagen_41001412010527\\tSM:Lineagen_41001412010527\\tPL:ILLUMINA'] # not used in current version of Snakefiles
manta_version: 'manta/1.6.0'
annotsv_version: 'annotsv/3.0.5'
deepvariant_version: 'deepvariant/1.1.0'
glnexus_version: 'glnexus/1.2.7'
picard_version:  'picard/2.23.7'
samtools_version: 'samtools/1.11'
gatk_version: 'GATK/3.8-0'
bazam_version: 'bazam/1.0.1'
bwa_version: 'bwa/0.7.17'
bwa-mem2_version: 'bwa-mem2/2.2.1'
biobambam2_version: 'biobambam2/2.0.179-release-20201228191456'
samblaster_version: 'samblaster/0.1.25'
sambamba_version: 'sambamba/0.8.1'
annovar_version: 'annovar/2019-10-24'
crossmap_version: 'crossmap/0.5.4'
#ref_genome: '/fdb/GATK_resource_bundle/b37-2.8/human_g1k_v37_decoy.fasta'
old_cram_ref: '/data/OGL/resources/1000G_phase2_GRCh37/human_g1k_v37_decoy.fasta'
bwa-mem2_ref: '/data/OGL/resources/genomes/NCBI/GRCh38Decoy/genome.fa' #GRCh37 is hard-coded in the Snakefile
ref_genome: '/data/OGL/resources/genomes/NCBI/GRCh38Decoy/genome.fa' ##GRCh37 is hard-coded in the Snakefile
GRCh38Decoy2: '/data/OGL/resources/genomes/GRCh38/bwa-mem2/GRCh38Decoy2.fa' #BCM duplicated regions masked
1000g_indels: '/fdb/GATK_resource_bundle/b37-2.8/1000G_phase1.indels.b37.vcf'
mills_gold_indels: '/fdb/GATK_resource_bundle/b37-2.8/Mills_and_1000G_gold_standard.indels.b37.vcf'
dbsnp_var: '/fdb/GATK_resource_bundle/b37-2.8/dbsnp_138.b37.excluding_sites_after_129.vcf'
R_version: 'R/3.6.3'
CoNVaDING_ctr_dir: '/data/OGVFB/OGL_NGS/CoNVaDING/OGLv1' # do not add "/" at the end.
chrRD_highcutoff: '1.2' # cutoff for producing the abnormal chromasomal read-depth file
chrRD_lowcutoff: '0.8' # cutoff for producing the abnormal chromasomal read-depth file
cutadapt_version: 'cutadapt/2.3'
R1_adaptor: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCA' #TrueSeq and NEB adaptors
R2_adaptor: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT' #TrueSeq and NEB adaptors
#INDELseek_bed: '/data/OGVFB/OGL_NGS/bed/OGL733v1.sorted.indelseek.bed' #Made by make_indelseek_bed.sh
freebayes_version: 'freebayes/1.3.5'
vcflib_version: 'vcflib/1.0.1'
vt_version: 'vt/0.57721'
vcftools_version: 'vcftools/0.1.16'
freebayes_exome_region: '/data/OGL/resources/freebayesRegion/xGenV1.10000.GRCh38.region' # panel 500 regions worked for MiSeq OGLv1; made by make_freebayes_region.sh. Exome 10,000 region file made with 64gmem of the bp 54390.markDup.bam file. Took ~ 20 min.
#freebayes_wgs_region: '/data/OGL/resources/freebayesRegion/v37d5/region'
#CRESTdb: '/data/OGL/resources/CRESTvariantClassification.xlsx'
SCRAMBLEdb: '/data/OGL/resources/SCRAMBLEvariantClassification.xlsx' # set in Snakefile for hg19 and hg38
scramble_version: 'scramble/1.0.1-32893ef'
mosdepth_version: 'mosdepth/0.2.8'
bedtools_version: 'bedtools/2.29.0'
OGL_Dx_research_genes: '/data/OGL/resources/OGLpanelGeneDxORcandidate.xlsx'
whatshap_version: 'whatshap/1.1'
HGMDtranscript: '/data/OGL/resources/HGMD/HGMDtranscript.txt'
