metadata_file: 'metadata_file.csv' # if making metadata file before running this snakemake, make sure the file name is metadata_file.csv. Otherwise, keep the file name as is.
analysis_batch_name: 'YYYYMMDD' # name for freebayes vcf file. If leaving as YYYYMMDD, current date will be used as name
ped: '' #Can leave as blank ''. Mainly for ChrX CNV, has to have ped extenstion, header if present has to starts with # miseq0626_0719.ped
inputFileType: 'fastq' # fastq, bam or cram.
cram: 'FALSE' # TRUE to convert bam to cram, values other than TRUE will not convert. #Keep bam for panel and exome, use cram for wgs
#recal_bam: 'FALSE' #TRUE to merge chr bams to single sample recalibrated bam
multiqc: 'TRUE' # will run only if TrueSeq
picardQC: 'TRUE'
CoNVaDING: 'FALSE'
SCRAMble: 'TRUE' #will run only if TRUE
GATKgvcf: 'TRUE' # will run only if TRUE
cutadapt: 'FALSE' #TRUE to trim adaptor using cutadapt, #FALSE not to trim.
CREST: 'TRUE' # TRUE or FALSE, TRUE for panel.Snakefile or exome only. WGS Snakefile does not have CREST, thus can keep as TRUE
regions: '/home/$USER/git/NGS_genotype_calling/NGS_generic_OGL/chr_split_24_coords.txt' #chr1 to chr22, chrX, chrY
freebayes: 'FALSE' # freebayes will run only if TRUE
freebayes_phasing: 'TRUE'
lane_pair_delim: ['_R1_001', '_R2_001'] #OGL & DavidM:'_R1_001', '_R2_001'
#samples: ['41001412010527_realigned_recal']
#read_groups: ['@RG\\tID:Lineagen_41001412010527\\tSM:Lineagen_41001412010527\\tPL:ILLUMINA'] # not used in current version of Snakefiles
picard_version:  'picard/2.17.11'
samtools_version: 'samtools/1.9'
gatk_version: 'GATK/3.8-0'
bwa_version: 'bwa/0.7.17'
annovar_version: 'annovar/2019-10-24'
ref_genome: '/fdb/GATK_resource_bundle/b37-2.8/human_g1k_v37_decoy.fasta'
bwa_genome: '/data/OGVFB/resources/1000G_phase2_GRCh37/human_g1k_v37_decoy.fasta'
1000g_indels: '/fdb/GATK_resource_bundle/b37-2.8/1000G_phase1.indels.b37.vcf'
mills_gold_indels: '/fdb/GATK_resource_bundle/b37-2.8/Mills_and_1000G_gold_standard.indels.b37.vcf'
dbsnp_var: '/fdb/GATK_resource_bundle/b37-2.8/dbsnp_138.b37.excluding_sites_after_129.vcf'
bed: '' # bed file is not used in the Snakefile for WGS or exome
R_version: 'R/3.6.3'
CoNVaDING_ctr_dir: '/data/OGVFB/OGL_NGS/CoNVaDING/OGLv1' # do not add "/" at the end.
chrRD_highcutoff: '1.2' # cutoff for producing the abnormal chromasomal read-depth file
chrRD_lowcutoff: '0.8' # cutoff for producing the abnormal chromasomal read-depth file
cutadapt_version: 'cutadapt/2.3'
R1_adaptor: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCA' #TrueSeq and NEB adaptors
R2_adaptor: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT' #TrueSeq and NEB adaptors
#INDELseek_bed: '/data/OGVFB/OGL_NGS/bed/OGL733v1.sorted.indelseek.bed' #Made by make_indelseek_bed.sh
freebayes_version: 'freebayes/1.3.1'
vcflib_version: 'vcflib/v1.0.0-rc0-331-g7e3d806'
vt_version: 'vt/0.57721'
vcftools_version: 'vcftools/0.1.16'
freebayes_exome_region: '/data/OGL/resources/freebayesRegion/bpExome.10000.region' # panel 500 regions worked for MiSeq OGLv1; made by make_freebayes_region.sh. Exome 10,000 region file made with largemem cpus-per-task=8, --mem=514g of the bp 54390.markDup.bam file. Took ~ 20 min. Alternatively could try downsampling a file: samtools view -bs 42.1 54390.markDup.bam > downsample.bam
freebayes_wgs_region: '/data/OGL/resources/freebayesRegion/v37d5/region'
CRESTdb: '/data/OGL/resources/CRESTvariantClassification.xlsx'
SCRAMBLEdb: '/data/OGL/resources/SCRAMBLEvariantClassification.xlsx'
OGL_Dx_research_genes: '/data/OGL/resources/OGLpanelGeneDxORcandidate.xlsx'
whatshap_version: 'whatshap/0.18'
HGMDtranscript: '/data/OGL/resources/HGMD/HGMDtranscript.txt'
