metadata_file: 'metadata_file.csv'
lane_pair_delim: ['_R1_001', '_R2_001']
samples: ['41001412010527_realigned_recal']
read_groups: ['@RG\\tID:Lineagen_41001412010527\\tSM:Lineagen_41001412010527\\tPL:ILLUMINA']
picard_version:  'picard/2.9.2'
samtools_version: 'samtools/1.6'
gatk_version: 'GATK/3.5-0'
bwa_version: 'bwa/0.7.12'
ref_genome: '/fdb/GATK_resource_bundle/b37-2.8/human_g1k_v37_decoy.fasta'
bwa_genome: '/data/mcgaugheyd/genomes/1000G_phase2_GRCh37/human_g1k_v37_decoy.fasta'
1000g_indels: '/fdb/GATK_resource_bundle/b37-2.8/1000G_phase1.indels.b37.vcf'
mills_gold_indels: '/fdb/GATK_resource_bundle/b37-2.8/Mills_and_1000G_gold_standard.indels.b37.vcf'
dbsnp_var: '/fdb/GATK_resource_bundle/b37-2.8/dbsnp_138.b37.excluding_sites_after_129.vcf'

